version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-187-23.eu-west-1.compute.amazonaws.com
            database: dffs2lptna97ut
            user: ilmhvruzylcqwx
            password: cdc656c73612c6c7fda510c3a7ce2bbcb263ab0a0a045981978c0f7ef81fc195
            rawAccess: true
            port: '5432'
            migrations: true
            ssl: true